export const notification = {
    sidenav_notifications: '[data-test="sidenav-notifications"]',
    list: '[data-test="notifications-list"]',
    list_header: '[data-test="empty-list-header"]',
    transaction_item: '.MuiGrid-root > .MuiGrid-container > .MuiGrid-spacing-xs-2 > .MuiGrid-grid-xs-true > .MuiTypography-body1',
    notifications_count: '[data-test="nav-top-notifications-count"]',
    like_button: '[data-test*="transaction-like-button"]',
    like_count: '[data-test*=transaction-like-count]',
    coments_list: '[data-test="comments-list"]',
    list_item: '[data-test*="notification-list-item"]',
    dismiss_button: '[data-test*="notification-mark-read"]',
    transaction_sender: '[data-test*="transaction-sender"]',
    transaction_action: '[data-test*="transaction-action"]',
    transaction_receiver: '[data-test*="transaction-receiver"]',
    link: '[data-test="nav-top-notifications-link"]',
    count: '[data-test="nav-top-notifications-count"]',
    comment_field: '[data-test="transaction-comment-input-7XaoAWOrn13"]',
    comment: '[data-test*="transaction-comment-input"]',
}
